# NumPy

    - NumPy (Numerical Python) is a Python library used for fast mathematical and scientific computing.It provides:

    - Multi-dimensional array object called ndarray
    - Tools for linear algebra, Fourier transforms, and random number generation
    - Vectorized operations (fast operations without writing loops)
    
**Uses of Numpy:

    - Speed – Much faster than Python lists for large datasets
    - Memory Efficiency – Stores data in compact binary format
    - Convenient Functions – Ready-made mathematical operations
    - Integration – Works with Pandas, Matplotlib, Scikit-learn, TensorFlow, etc.

**Key Features:

    - ndarray: Powerful n-dimensional array
    - Broadcasting: Perform operations on arrays of different shapes
    - Vectorization: No need for Python for loops
    - Mathematical Functions: sum(), mean(), sqrt(), etc.
    - Indexing/Slicing: Extract data easily
    - Random Module: Random number generation

**Advantages Over Python Lists

| Feature      | Python List   | NumPy Array       |
| ------------ | ------------- | ----------------- |
| Speed        | Slow          | Very Fast         |
| Memory Usage | High          | Low               |
| Operations   | Need loops    | Vectorized        |
| Data Types   | Mixed allowed | Single fixed type |



    **Rows → Go horizontally (left to right)
    **Columns → Go vertically (top to bottom)

|           | **Column 0** | **Column 1** | **Column 2** |
| --------- | ------------ | ------------ | ------------ |
| **Row 0** | 10           | 20           | 30           |
| **Row 1** | 40           | 50           | 60           |
| **Row 2** | 70           | 80           | 90           |


# Array Creation

In [1]:
# Create a list:

l = [1,2,3,4,5,3.14,True,1+2j,"MOIZ"]   # in list we can stores multiple types of data types.
l

[1, 2, 3, 4, 5, 3.14, True, (1+2j), 'MOIZ']

In [2]:
print(type(l))     # list

<class 'list'>


#Create a Array using List:

#First of all to create a Array we neet to import numpy library in your python program.

In [3]:
import numpy as np   # we imported the numpy labrary, numpy as np.

In [4]:
arr = np.array(l)     # numpy only contain same type of data types . np converted mixed data types to same data type.
arr                  # we create a array using python list.

array(['1', '2', '3', '4', '5', '3.14', 'True', '(1+2j)', 'MOIZ'],
      dtype='<U64')

In [5]:
arr1 = np.array([1,2,3])      # we create a new array
arr1

array([1, 2, 3])

In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])     # this is 1D (one Dimentional)array . this array in the form of vector.
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
l1 = [1,2,3],[4,5,6],[7,8,9]    # this list is 1D 
l1

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [9]:
# convert One Dimension (1D) to Two Dimension (2D) array:

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy Arrays Vs Python Sequences


NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
Changing the size of an ndarray will create a new array and delete the original.
The elements in a NumPy array are all required to be of the same data type, and thus will be
the same size in memory.
NumPy arrays facilitate advanced mathematical and other types of operations on large
numbers of data. Typically, such operations are executed more efficiently and with less code
than is possible using Python’s built-in sequences.
A growing plethora of scientific and mathematical Python-based packages are using NumPy
arrays; though these typically support Python-sequence input, they convert such input to
NumPy arrays prior to processing, and they often output NumPy arrays.

# Array Generation Function:

# Arange:

    - np.arange() is a NumPy function that creates an array with evenly spaced values within a specified range.
    - It’s like Python’s built-in range() but:
    
        - It returns a NumPy array instead of a list.
        - It can work with decimal (float) steps, not just integers.


-Syntax : np.arange(start, stop, step, dtype=None)

**Parameters:

            - Start → The starting value (inclusive). Default = 0 if not given.
            - Stop → The ending value (exclusive, not included).
            - Step → The gap between values. Default = 1.
            - dtype → Data type of the output (optional).


**Difference from np.linspace()

                        - np.arange(start, stop, step) → You give step size.
                        - np.linspace(start, stop, num) → You give how many values you want.

In [10]:
s = np.arange(9)    # created a array by using arange function.
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr = np.arange(1,11) # print array from 1 to 11. endending endex i not encluded.step by default 1. 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a = np.arange(1,50)   # this is in 1D (vector)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
b = np.arange(1,21,2) # Step → The gap between values 2.
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Zeros:

    - np.zeros() creates a new array filled entirely with 0s.
    - It’s useful when you want an empty container to store future data, or when you need a base array for calculations.

**Syntax: np.zeros(shape, dtype=float)

**Parameters:

        - Shape → Size of the array.
        - Can be an integer (for 1D) or a tuple (for multi-dimensional arrays).
        - dtype → Data type of the elements. Default is float.

In [14]:
arr = np.zeros(5) # array in vector form by default data type of element is float.
arr

array([0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((4,4))     # now array is in matrix and 2D form. but by default data type of element is float.
arr                       # 4,4 means [4 rows & 4 columns].

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Change the data type of element of above matrix:

arr = np.zeros((4,4),dtype=int)   # we converted float data type to int data type(Type Casting).
arr                               

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
arr = np.zeros((6,5),dtype=int) # 6 rows & 5 columns.
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Ones:

    - np.ones() creates a new array filled entirely with 1s.
    - It’s often used when you need a base array for calculations or initialization where all values start as 1.

**Syntax : np.ones(shape, dtype=float)

**Parameters:

    - Shape → Size of the array.
    - Integer → for 1D arrays.
    - Tuple → for multi-dimensional arrays.
    - dtype → Data type of the elements (default: float).

**Common Uses

    - Mathematical calculations (when multiplying or adding values).
    - Masking in data science (representing “all True” conditions).
    - Matrix initialization for algorithms.

In [18]:
arr = np.ones(9)    # create a array using ones(),by default data type of element is float.
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# convert above 1D matrix to 2D matrix:

arr = np.ones((5,5))  # 2D matrix
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# convert Data type of element from float to int data type:

arr = np.ones((5,5),dtype=int)    # converted float to int (Type Casting).
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
arr = np.ones((10,10),dtype=int)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# Random:

    - np.random is a module inside NumPy that can generate random numbers.
    - It can produce:
    - Floats (decimal numbers)
    - Integers
    - Arrays with random values
    - Numbers from specific probability distributions (normal, uniform, etc.)

**Summary Table:

| Function       | Output Type | Range / Distribution |
| -------------- | ----------- | -------------------- |
| `rand()`       | float       | 0 to 1 (uniform)     |
| `randint(a,b)` | int         | a to b-1 (uniform)   |
| `randn()`      | float       | Normal dist (mean=0) |
| `random()`     | float       | 0 to 1 (uniform)     |
| `choice()`     | any element | From given sequence  |


In [23]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
arr = np.random.rand(2,3)
arr

array([[0.37382351, 0.22060975, 0.55619742],
       [0.64560009, 0.02616842, 0.34177492]])

In [25]:
np.random.rand(2,5)

array([[0.05518729, 0.53926395, 0.44913536, 0.51589408, 0.47004495],
       [0.41340683, 0.49630755, 0.45165112, 0.85272395, 0.27106902]])

In [26]:
np.random.randint(1, 10, (2, 4))    # Generate random integer number. use randint()

array([[6, 3, 7, 6],
       [3, 7, 9, 7]], dtype=int32)

In [27]:
np.random.randn(10) # standidisation

array([-0.88525304, -0.53177207, -2.42712425, -1.63241698, -0.12972767,
        1.66581448, -0.77301698, -2.20817337,  0.06765331,  0.79749708])

In [28]:
np.random.randint(10,15,4)  # print4 random number between 10 and 15.

array([10, 13, 11, 11], dtype=int32)

# Linspace:

    - In NumPy, the linspace() function is used to create a sequence of evenly spaced numbers over a specified range.

**Syntax : np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

**Parameters:

    - Start – The starting value of the sequence.
    - Stop – The end value of the sequence.
    - Num (optional) – Number of values to generate (default = 50).
    - Endpoint (optional) –
    - True (default): Includes the stop value in the sequence.
    - False: Excludes the stop value.
    - Retstep (optional) –
    - True: Returns both the array and the spacing between values.
    - False (default): Returns only the array.
    - dtype (optional) – The type of the output array (e.g., int, float).

**Key Difference from arange()

    - linspace() is based on number of elements you want.
    - arange() is based on the step size.


# identity

indentity matrix is that diagonal items will be ones and evrything will be zeros


In [29]:
# creating the indentity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Linspace
    
    - start → The first value in the range (here 1).
    - stop → The last value in the range (here 10).
    - Blue dots → Evenly spaced numbers generated between start and stop.
    - evenly spaced → Means the interval (gap) between consecutive numbers is the same.

In [31]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
arr = np.linspace(1,2,5) # step count
arr

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
arr = np.linspace(1,10,num=20,dtype=int)
arr

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

In [34]:
arr2 = np.linspace(2,6,num=7)

In [35]:
arr2

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        ])

In [36]:
# convert the above code into int data type:

arr2 = np.linspace(2,6,num=7,dtype=int)
arr2

array([2, 2, 3, 4, 4, 5, 6])

# Max & Min

In [37]:
print(np.max(arr2))

6


In [38]:
print(np.max(arr))

10


In [39]:
print(np.min(arr))

1


In [40]:
print(np.min(arr2))

2


In [41]:
print(np.sum(arr))

101


In [42]:
print(np.sum(arr2))

26


In [43]:
# prod ----> Multiplication

print(np.prod(arr))

1316818944000


In [44]:
print(np.prod(arr2))

5760


In [45]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# if we want maximum of every row

np.max(a, axis = 1)

array([3, 6, 9])

In [47]:
# maximum of every column

np.max(a, axis = 0)

array([7, 8, 9])

In [48]:
# product of every column

np.prod(a, axis = 0)

array([ 28,  80, 162])

# Mathematical Functions

    - In NumPy, mathematical functions are divided into several categories — they work element-wise on arrays and are highly optimized for speed.
                                                                                                                                      
**Here’s a structured list                                                                                                                                      

| Function            | Description    | Example                              |
| ------------------- | -------------- | ------------------------------------ |
| `np.add(a, b)`      | Addition       | `np.add([1,2],[3,4]) → [4 6]`        |
| `np.subtract(a, b)` | Subtraction    | `np.subtract([5,4],[2,3]) → [3 1]`   |
| `np.multiply(a, b)` | Multiplication | `np.multiply([2,3],[4,5]) → [8 15]`  |
| `np.divide(a, b)`   | Division       | `np.divide([10,20],[2,5]) → [5. 4.]` |
| `np.power(a, b)`    | Exponentiation | `np.power([2,3],[3,2]) → [8 9]`      |
| `np.mod(a, b)`      | Modulus        | `np.mod([10,15],[3,4]) → [1 3]`      |


In [49]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [50]:
# Addition of a1 & a2 :

a1 + a2

array([ 7,  9, 11, 13, 15])

In [51]:
# Substracton of a1 & a2 :

a1 - a2

array([-5, -5, -5, -5, -5])

In [52]:
# Division of a1 & a2 :

a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [53]:
# int Division of a1 & a2 :

a1 // a2

array([0, 0, 0, 0, 0])

In [54]:
# multiplication of a1 & a2 :

a1 * a2

array([ 6, 14, 24, 36, 50])

In [55]:
# Power of a1 & a2:

a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [56]:
a = np.array([1,11])
print(a)
b = np.array([10,21])
print(b)

[ 1 11]
[10 21]


In [57]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [58]:
s = np.subtract([6,4],[2,15])     # substract 2 each elememnt
s

array([  4, -11])

In [59]:
d = np.divide(a,2)
d

array([0.5, 5.5])

In [60]:
m = np.multiply([7,2],[3,16])
m

array([21, 32])

# Statistical Functions

    - In NumPy, “Statistical Functions” are built-in methods that help you quickly calculate key statistics on numerical data stored in arrays.
    - They work element-wise or on the whole array, and you can also specify an axis for row-wise or column-wise results.

**1. Central Tendency Functions:

| Function                      | Description               | Example                                      |
| ----------------------------- | ------------------------- | -------------------------------------------- |
| `np.mean(a)`                  | Arithmetic mean (average) | `np.mean([1,2,3]) → 2.0`                     |
| `np.median(a)`                | Middle value when sorted  | `np.median([1,3,2]) → 2.0`                   |
| `np.average(a, weights=None)` | Weighted average          | `np.average([1,2,3], weights=[1,2,1]) → 2.0` |



**2. Spread (Dispersion) Functions:

| Function    | Description        | Example                    |
| ----------- | ------------------ | -------------------------- |
| `np.std(a)` | Standard deviation | `np.std([1,2,3]) → 0.8165` |
| `np.var(a)` | Variance           | `np.var([1,2,3]) → 0.6667` |


**3. Min, Max, and Related:

| Function    | Description     | Example               |
| ----------- | --------------- | --------------------- |
| `np.min(a)` | Minimum value   | `np.min([5,1,9]) → 1` |
| `np.max(a)` | Maximum value   | `np.max([5,1,9]) → 9` |
| `np.ptp(a)` | Range (max-min) | `np.ptp([5,1,9]) → 8` |




In [61]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [62]:
m = np.array([1,2,3,4,5,6,7,8])
mean = np.mean(s)
print("mean of m is :",mean)

mean of m is : 2.5


# Array Attributes

    - In NumPy, array attributes give you important information about the structure, size, shape, and type of an array.
    - They are not methods (so no ()), they are properties you access directly.

**Common NumPy Array Attributes:

| Attribute              | Description                                       | Example                      |
| ---------------------- | ------------------------------------------------- | ---------------------------- |
| **`ndarray.ndim`**     | Number of dimensions (axes)                       | `a.ndim → 2`                 |
| **`ndarray.shape`**    | Tuple of array dimensions (rows, cols, etc.)      | `a.shape → (3, 4)`           |
| **`ndarray.size`**     | Total number of elements                          | `a.size → 12`                |
| **`ndarray.dtype`**    | Data type of array elements                       | `a.dtype → dtype('int32')`   |
| **`ndarray.itemsize`** | Size in bytes of one element                      | `a.itemsize → 4` (for int32) |
| **`ndarray.nbytes`**   | Total bytes consumed (`size × itemsize`)          | `a.nbytes → 48`              |
| **`ndarray.T`**        | Transposed version of array                       | `a.T`                        |
| **`ndarray.real`**     | Real part (for complex arrays)                    | `a.real`                     |
| **`ndarray.imag`**     | Imaginary part (for complex arrays)               | `a.imag`                     |
| **`ndarray.data`**     | Memory buffer of the array (rarely used directly) | `a.data`                     |


In [63]:
a1 = np.arange(10) # 1D
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a2 =np.arange(12, dtype =float).reshape(3,4) # Matrix
a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [65]:
a3 = np.arange(8).reshape(2,2,2) # 3D --> Tensor
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim
    - To findout given arrays number of dimensions


In [66]:
a1.ndim


1

In [67]:
a2.ndim


2

In [68]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
a3.ndim

3

In [70]:
print("Array:\n", a)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# shape
    - gives each item consist of no.of rows and np.of column


In [71]:
a1.shape # 1D array has 10 Items

(10,)

In [72]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [73]:
a.shape    #uple of array dimensions (rows, cols, etc.)

(3, 3)

In [74]:
a3.shape # first ,2 says it consists of 2D arrays .2,2 gives no.of rows and c

(2, 2, 2)

# size
    - gives number of items

In [75]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
a3.size # it has 8 items . like shape :2,2,2 = 8

8

In [77]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [78]:
a2.size

12

# item size
    - Memory occupied by the item


In [79]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a1.itemsize # bytes


8

In [81]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [82]:
a2.itemsize # integer 64 gives = 8 bytes

8

In [83]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3.itemsize # integer 32 gives = 4 bytes

8

# dtype
    - gives data type of the item


In [85]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [86]:
a.dtype  #  Data type of array items  

dtype('int64')

# Changing Data Type


In [87]:
#astype

x = np.array([33, 22, 2.5])
x

array([33. , 22. ,  2.5])

In [88]:
x.astype(int)

array([33, 22,  2])

In [89]:
y = np.array([5,7,7.9])
y

array([5. , 7. , 7.9])

In [90]:
y.astype(int)

array([5, 7, 7])

# Array Methods

In [91]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
print(arr3.max()) # maximum number in the list

9


In [93]:
print(arr3.min()) # print smallest in the list

1


In [94]:
print(arr3.sum()) # addition of matrix

45


In [95]:
print(np.sum(arr3,0))   # Addition of COULMN

[12 15 18]


In [96]:
print(np.sum(arr3,1))  # Addition of ROWS in the matrix.

[ 6 15 24]


In [97]:
print(np.mean(arr3))   # mean position

5.0


In [98]:
print(np.std(arr3))# Standerd daviation

2.581988897471611


In [99]:
print(np.argmax(arr3))# maximum element index number

8


In [100]:
print(np.argmin(arr3))   # minimun element index number

0


# Reshape & Resizing

**1. reshape() – Change Shape Without Changing Data
 
        - Purpose: Changes the dimensions (shape) of an array without changing the data.
        - Important: The total number of elements must remain the same.

**Syntax : numpy.reshape(a, newshape) , or : arr.reshape(newshape)


**2. resize() – Change Shape AND Size

        - Purpose: Changes shape and can change the total number of elements.
        - Difference from reshape:
        - resize() modifies the original array (in-place if called as a method).
        - If the new size is bigger, extra elements are filled with zeros.
        - If smaller, extra data is truncated.

**Syntax :  numpy.resize(a, new_shape)   # Returns new array
            arr.resize(new_shape)        # Changes array in place


Key Differences:

| Feature                | `reshape()`           | `resize()`                     |
| ---------------------- | --------------------- | ------------------------------ |
| Changes element count? | ❌ No                  | ✅ Yes                          |
| Creates a copy?        | Sometimes (if needed) | Optional (can modify original) |
| Keeps original array?  | ✅ Yes                 | ❌ Can overwrite                |
| Fills missing values?  | ❌ No                  | ✅ Yes, with zeros              |



In [101]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [102]:
# convert above 1D array into 2D array using reshape function:

arr.reshape(6,5) # Convertd 1D to 2D array.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# reshape

Both of number products should be equal to umber of Items present inside the array.

In [103]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [104]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [105]:
np.arange(1,13).reshape(3,4) # converted 3 rows and 4 columns


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Resize 

    - Purpose: Return a new array with the specified shape.
    - It does not modify the original array.
    - If the new shape is larger than the original, it repeats the array elements to fill the space.

    - Use np.resize() if you want a new array and don’t want to touch the original.
    - Use arr.resize() if you want to change the original array in-place

In [106]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [107]:
resize = np.resize(arr,(2,2))
resize

array([[1, 2],
       [3, 4]])

In [108]:
rsz = np.resize(arr,(4,4))   # "The new array needs 4×4 = 16 elements → [1, 2, 3, 4, 5 1, 2, 3, 4, 5 1, 2, ...] are repeated."
rsz

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2],
       [3, 4, 5, 1]])

In [109]:
s = np.resize(arr,(6,6)) # "The new array needs 6 X 6 = 36 elements → [1, 2, 3, 4, 5 1, 2, 3, 4, 5 1, 2, ...] are repeated."
rsz
s

array([[1, 2, 3, 4, 5, 1],
       [2, 3, 4, 5, 1, 2],
       [3, 4, 5, 1, 2, 3],
       [4, 5, 1, 2, 3, 4],
       [5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1]])

# Indexing & Slicing of Vectors:

**1. Indexing in NumPy

        - Indexing means accessing elements from an array.
        - NumPy supports 0-based indexing (first element index is 0).

**2. Slicing in NumPy

        - Slicing extracts a range of elements from an array.

In [110]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [111]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Indexing on 1D array

In [114]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
# fetchig first ietm

print(p1[0])

0


In [116]:
# fetching last item

print(p1[-1])

9


In [117]:
# 1D Array:

arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [118]:
# Indexing:

print(arr[0])       # zeroth index.

11


In [119]:
print(arr[5]) # 5th index number that is 16.

16


In [120]:
print(arr[9]) 

20


# Slicing on 1D

In [121]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [122]:
# 1D Slicing:

print(arr[0 : 6])     # slicing from 0th index to 6th index number.

[11 12 13 14 15 16]


In [123]:
print(arr[3 : ])  # slicing from 3rd index to last , by default after colon not mention is as the till the last.


[14 15 16 17 18 19 20]


In [124]:
print(arr[ : 6])  # slicing from oth index to 6th index

[11 12 13 14 15 16]


In [125]:
arr_1 = print(arr[0 : 9 : 2]) # step slicing.
arr_1

[11 13 15 17 19]


# Slicing on 2D



| Slice Syntax    | Meaning                          |
| --------------- | -------------------------------- |
| `mat[0:2, :]`   | First 2 rows, all columns        |
| `mat[:, 1:3]`   | All rows, columns 1 and 2        |
| `mat[::2, ::2]` | Every 2nd row & every 2nd column |
| `mat[-1, :]`    | Last row, all columns            |
| `mat[:, -1]`    | All rows, last column            |


In [126]:
mat = np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
mat[0] # Rows

array([1, 2, 3])

In [128]:
mat[1] # Rows

array([4, 5, 6])

In [129]:
mat[2]  # Rows

array([7, 8, 9])

In [130]:
mat[:,0]  # columns

array([1, 4, 7])

In [131]:
mat[:,1]   # columns

array([2, 5, 8])

In [132]:
mat[:,2]   # columns

array([3, 6, 9])

In [133]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
mat[1:3]    # 1st row and 2nd row

array([[4, 5, 6],
       [7, 8, 9]])

In [135]:
mat[0:3]  # 0th to 3rd row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
mat[:,0:2]    # Columns slicing

array([[1, 2],
       [4, 5],
       [7, 8]])

In [137]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
# fetching total First row
p2[0, :]

array([0, 1, 2, 3])

#EXPLANATION :Here 0 represents first row and (:) represnts Total column

In [139]:
# fetching total third column
p2[:,2]

array([ 2,  6, 10])

#EXPLANATION :Here we want all rows so (:) , and we want 3rd column so 2

In [140]:
# fetch 5,6 and 9,10
p2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
p2[1:3] # for rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
p2[1:3 ,1:3] # For columns

array([[ 5,  6],
       [ 9, 10]])

#EXPLANATION :Here first [1:3] we slice 2 second row is to third row is not existed which is 2
and Secondly , we take [1:3] which is same as first:we slice 2 second row is to third row is not
included which is 3

In [143]:
# fetch 0,3 and 8,11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [145]:
# fetch 1,3 and 9,11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
p2[::2] # For rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [147]:
p2[::2 ,1::2] # columns

array([[ 1,  3],
       [ 9, 11]])

In [149]:
p2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

EXPLANATION : Here we take (:) because we want all rows , second(:2) for alternate value,
and (1) for we want from second column and (:2) jump for two steps and ignore middle one

In [150]:
# fetch only 4 ,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
p2[1] # first rows

array([4, 5, 6, 7])

In [152]:
p2[1,::3] # second columns

array([4, 7])

EXPLANATION : Here we take (1) because we want second row , second(:) for total column,
(:3) jump for two steps and ignore middle ones

In [153]:
# fetch 1,2,3 and 5,6,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
p2[0:2] # first fetched rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [155]:
p2[0:2 ,1: ] # for column

array([[1, 2, 3],
       [5, 6, 7]])

In [156]:
# fetch 1,3 and 5,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
p2[0:2] # for rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [158]:
p2[0:2 ,1::2]

array([[1, 3],
       [5, 7]])

#EXPLANATION : 0:2 selects the rows from index 0 (inclusive) to index 2 (exclusive), which
means it will select the first and second rows of the array. , is used to separate row and column
selections. 1::2 selects the columns starting from index 1 and selects every second column. So
it will select the second and fourth columns of the array.


# Slicing in 3D

In [159]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [160]:
# fetch second matrix
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [161]:
# fetch first and last
p3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#EXPLANATION : Along the first axis, (::2) selects every second element. This means it will
select the subarrays at indices 0 and 2

In [162]:
# Fetch 1 2d array's 2 row ---> 3,4,5
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [163]:
p3[0] # first numpy array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
p3[0,1,:]


array([3, 4, 5])

#EXPLANATION : 0 represnts first matrix , 1 represents second row , (:) means total

In [165]:
# Fetch 2 numpy array ,middle column ---> 10,13,16
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [166]:
p3[1] # middle Array

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [167]:
p3[1,:,1]

array([10, 13, 16])

#EXPLANATION : 1 respresnts middle column , (:) all columns , 1 represnts middle column

In [168]:
# Fetch 3 array--->22,23,25,26
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [169]:
p3[2] # last row

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [170]:
p3[2, 1: ] # last two rows

array([[21, 22, 23],
       [24, 25, 26]])

In [171]:
p3[2, 1: ,1:] # last two columns

array([[22, 23],
       [25, 26]])

#EXPLANATION : Here we go through 3 stages , where 2 for last array , and (1:) from second
row to total rows , and (1:) is for second column to total columns

In [172]:
# Fetch o, 2, 18 , 20
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [173]:
p3[0::2] # for arrays

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [174]:
p3[0::2 , 0] # for rows

array([[ 0,  1,  2],
       [18, 19, 20]])

In [175]:
p3[0::2 , 0 , ::2] # for columns

array([[ 0,  2],
       [18, 20]])

#EXPLANATION : Here we take (0::2) first adn last column , so we did jump using this, and we
took (0) for first row , and we (::2) ignored middle column

# Boolean Indexing in Numpy:

**What is Boolean Indexing?

                - Boolean indexing means filtering array elements using a True/False condition.
                - You create a boolean mask (array of True/False) based on a condition.
                - NumPy then selects only the elements where the mask is True.

In [176]:
arr= np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [177]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [178]:
arr = arr[bool_index]

In [179]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Iterating

In [180]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
# Looping on 1D array
for i in p1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [182]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
## Looping on 2D array
for i in p2:
    print(i) # prints rows

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [184]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [185]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


#print all items in 3D using nditer ----> first convert in to 1D and applying Loop

In [186]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

# Transpose ---> Converts rows in to clumns ad columns into rows

In [187]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [189]:
# Another method
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [190]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [191]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# Ravel

In [192]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [193]:
p2.ravel()    # convert 2D into vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [194]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [195]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

    - Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked


In [196]:
# Horizontal stacking
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [197]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [199]:
# using hstack for Horizontal stacking

np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [200]:
# Vertical stacking
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#using vstack for vertical stacking

In [202]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

    - its opposite of Stacking

In [203]:
# Horizontal splitting
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
np.hsplit(w1,2) # splitting by 2

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [205]:
np.hsplit(w1,4) # splitting by 4


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [206]:
# Vertical splitting
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [207]:
np.vsplit(w2,3) # splittig into 3 rows

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# Broadcasting

In [208]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
s = a + 10      # add 10 in the matrix.
s

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [210]:
a 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [211]:
l = a * 2 /3
l

array([[ 0.66666667,  1.33333333,  2.        ,  2.66666667,  3.33333333],
       [ 4.        ,  4.66666667,  5.33333333,  6.        ,  6.66666667],
       [ 7.33333333,  8.        ,  8.66666667,  9.33333333, 10.        ],
       [10.66666667, 11.33333333, 12.        , 12.66666667, 13.33333333],
       [14.        , 14.66666667, 15.33333333, 16.        , 16.66666667]])

# Deep & Shapllo Copy :


In [212]:
z = np.arange(1,16)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [213]:
s = slice = z[:6]
s = slice
s

array([1, 2, 3, 4, 5, 6])

In [214]:
s = slice = z[:6]
s = slice * 2
s

array([ 2,  4,  6,  8, 10, 12])

In [215]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [216]:
s = z.copy()
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [217]:
print(id(z))
print(id(s))

2556458533104
2556458534736


In [218]:
s[0] = 99
s

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [219]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [220]:
id(z)

2556458533104

In [221]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [222]:
a

array([[1, 2],
       [3, 4]])

In [223]:
b

array([[5, 6],
       [7, 8]])

In [224]:
a @ b

array([[19, 22],
       [43, 50]])

In [225]:
np.dot(a,b)  # Second method of multiplication

array([[19, 22],
       [43, 50]])

In [226]:
# Transpose:
            # means it convrt rows to columns and columns to rows.

a

array([[1, 2],
       [3, 4]])

In [227]:
b

array([[5, 6],
       [7, 8]])

In [228]:
a.T  # rows to columns

array([[1, 3],
       [2, 4]])

In [229]:
b.T 

array([[5, 7],
       [6, 8]])

# Advance array manupilation

- Stacking Array

In [230]:
a = [[1,2,3,4,5]]
b = [[6,7,8,9,10]]

In [231]:
a

[[1, 2, 3, 4, 5]]

In [232]:
b

[[6, 7, 8, 9, 10]]

In [233]:
h = np.hstack((a,b))
h

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [234]:
v = np.vstack((a,b))
v

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [235]:
a

[[1, 2, 3, 4, 5]]

In [236]:
b

[[6, 7, 8, 9, 10]]

In [237]:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [238]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [239]:
np.hsplit(A,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [240]:
np.hsplit(A,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [241]:
np.vsplit(A,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]