# Numpy

    - NumPy (Numerical Python) is a Python library used for fast mathematical and scientific computing.It provides:

    - Multi-dimensional array object called ndarray
    - Tools for linear algebra, Fourier transforms, and random number generation
    - Vectorized operations (fast operations without writing loops)
    
**Uses of Numpy:

    - Speed – Much faster than Python lists for large datasets
    - Memory Efficiency – Stores data in compact binary format
    - Convenient Functions – Ready-made mathematical operations
    - Integration – Works with Pandas, Matplotlib, Scikit-learn, TensorFlow, etc.

**Key Features:

    - ndarray: Powerful n-dimensional array
    - Broadcasting: Perform operations on arrays of different shapes
    - Vectorization: No need for Python for loops
    - Mathematical Functions: sum(), mean(), sqrt(), etc.
    - Indexing/Slicing: Extract data easily
    - Random Module: Random number generation

**Advantages Over Python Lists

| Feature      | Python List   | NumPy Array       |
| ------------ | ------------- | ----------------- |
| Speed        | Slow          | Very Fast         |
| Memory Usage | High          | Low               |
| Operations   | Need loops    | Vectorized        |
| Data Types   | Mixed allowed | Single fixed type |


In [2]:
import numpy as np       # import numpy → Loads the NumPy library so you can use its functions.
                         # as np → Creates a short alias np for NumPy, so instead of typing numpy.array(),
                         # you can type np.array() (less typing, cleaner code).

In [3]:
np.__version__

'2.1.3'

In [4]:
l = [0,1,2,3,4,5]     # Create a list
l

[0, 1, 2, 3, 4, 5]

In [5]:
print(type(l))     # type of l

<class 'list'>


In [6]:
arr = np.array(l)        # create a Array
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
print(type(arr))   #type of arr

<class 'numpy.ndarray'>


# Indexing and Slicing

In [70]:
mat = np.arange(0,100).reshape(10,10)

In [33]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
row = 4
col = 5

In [36]:
row

4

In [37]:
col

5

In [38]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
print(mat[row,col])   # means access the single element at the given row and column position.

45


In [71]:
print(mat[3,6])     #  # means access the single element at the given row and column position.

36


In [40]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
mat[:] # Slicing    # in NumPy, it means “take all rows and all columns”,Often used when slicing subsets.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
col = 5 
col

5

In [43]:
mat[7] # indexing

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[:,col] # how to print column , we need to must sclicing[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [46]:
mat[col] # how to print rows [col]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [47]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
mat[:,-1]   # print reverse coulmn

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [49]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
row

4

In [51]:
mat[row,:]  # row indexing , 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [59]:
row = 4
col = 5

4

In [61]:
row

4

In [62]:
col

5

In [63]:
mat[row:]  

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
mat[:row]       # we mntion above row is equal to 4 then ,print Row from start to row 4.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [65]:
mat[:,col]  # above mention that column is equal to 5 then print colomn number is 5.

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [55]:
mat[:,4]   # we print colomn

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [56]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [67]:
# means slice a block of rows and columns from a 2D array.

mat[4:6,2:7]        # 4:6 → Take rows from index 4 up to (but not including) index 6
                    # 2:7 → Take columns from index 2 up to (but not including) index 7

array([[42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56]])

In [68]:
# means slice a block of rows and columns from a 2D array.

mat[3:8,7:9]

array([[37, 38],
       [47, 48],
       [57, 58],
       [67, 68],
       [77, 78]])

In [69]:
# means slice a block of rows and columns from a 2D array.

mat[4:6,2:4]

array([[42, 43],
       [52, 53]])